language: bash

services:
  - docker

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_SERVER"

script:
  - uname -a
  - env
  - echo "${TRAVIS_COMMIT:0:7}"

after_success:
  - docker build -t "$DOCKER_SERVER/ztj1993/travis:${TRAVIS_BRANCH}" .
  - docker push "$DOCKER_SERVER/ztj1993/travis:${TRAVIS_BRANCH}"
