language: bash

before_install:
  - COMMIT_ALIAS=${TRAVIS_COMMIT:0:7}
  - git clone --no-checkout --depth 1 https://github.com/ztj1993/scoop-index /scoop
  - git -C /scoop checkout master
  - git -C /scoop checkout master
  - git -C /scoop submodule init
  - git -C /scoop submodule update --depth 1
  - git -C /scoop/apps/scoop/current am /scoop/patch/disable-automatic-update.patch
  - zip -r /scoop-${COMMIT_ALIAS}.zip /scoop

install: skip

before_script: skip

script: skip

after_success: skip

after_failure: skip

before_deploy: skip

after_deploy: skip

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - /scoop-${COMMIT_ALIAS}.zip
  on:
    all_branches: true
    tags: true

after_script: skip
