language: bash

before_install:
  - sudo mkdir /scoop && sudo chmod 777 /scoop && cd /scoop
  - git clone --depth 1 https://github.com/ztj1993/scoop-index .
  - git submodule init
  - git submodule update --depth 1
  - git -C apps/scoop/current am patch/disable-automatic-update.patch

install: skip

before_script: skip

script: skip

after_success: skip

after_failure: skip

before_deploy: skip

after_deploy: skip

after_script: skip
