language: bash

before_install:
  - sudo mkdir /app && sudo chmod 777 /app && cd /app
  - git clone --depth 1 https://github.com/ztj1993/scoop-index .
  - git submodule init
  - git submodule update --depth 1

install: skip

before_script: skip

script: skip

after_success: skip

after_failure: skip

before_deploy: skip

after_deploy: skip

after_script: skip
