language: bash

services:
  - docker

before_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" "${DOCKER_SERVER}"
  - TAG_BASE="${TRAVIS_BRANCH}"
  - TAG_EXT="${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}"
  - IMAGE_BASE="${DOCKER_SERVER}/${TRAVIS_REPO_SLUG}:${TAG_BASE}"
  - IMAGE_EXT="${DOCKER_SERVER}/${TRAVIS_REPO_SLUG}:${TAG_EXT}"

script:
  - docker build -t "${TAG_BASE}" .
  - docker build -t "${TAG_EXT}" .
  - docker run --rm --name=${TAG_BASE} ${TAG_BASE} env

after_success:
  - docker push "${IMAGE_BASE}"
  - docker push "${IMAGE_EXT}"
  - echo "${IMAGE_BASE}"
  - echo "${IMAGE_EXT}"
