language: bash

services:
  - docker

before_install:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" "${DOCKER_SERVER}"
  - TAG_BASE="${TRAVIS_BRANCH}"
  - TAG_EXT="${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}"
  - IMAGE_BASE="${DOCKER_SERVER}/${TRAVIS_REPO_SLUG}:${TAG_BASE}"
  - IMAGE_EXT="${DOCKER_SERVER}/${TRAVIS_REPO_SLUG}:${TAG_EXT}"

install:
  - docker build -t "${IMAGE_BASE}" -t "${IMAGE_EXT}" .

before_script: skip

script:
  - docker run --rm --name=${TAG_BASE} ${IMAGE_BASE} ls
  - docker run --rm --name=${TAG_BASE} ${IMAGE_BASE} cat /srv/package.json

after_success:
  - echo "${IMAGE_BASE}"
  - echo "${IMAGE_EXT}"

after_failure: skip

before_deploy: skip

after_deploy: skip

after_script: skip
