language: bash

services:
  - docker

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_SERVER"

script:
  - uname -a
  - env

after_success:
  - docker build -t "$DOCKER_SERVER/ztj1993/travis:latest" .
  - docker push "$DOCKER_SERVER/ztj1993/travis:latest"
