language: bash

services:
  - docker

before_install:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" "${DOCKER_SERVER}"
  - TAG_BASE="${TRAVIS_BRANCH}"
  - TAG_EXT="${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}"
  - IMAGE_BASE="${DOCKER_SERVER}/${TRAVIS_REPO_SLUG}:${TAG_BASE}"
  - IMAGE_EXT="${DOCKER_SERVER}/${TRAVIS_REPO_SLUG}:${TAG_EXT}"

install:
  - docker build -t "${IMAGE_BASE}" -t "${IMAGE_EXT}" .

before_script: skip

script:
  - docker build -t "${IMAGE_BASE}" .
  - docker build -t "${IMAGE_EXT}" .
  - docker run --rm --name=${TAG_BASE} ${IMAGE_BASE} python -V
  - docker run --rm --name=${TAG_BASE} ${IMAGE_BASE} pip -V
  - docker run --rm --name=${TAG_BASE} ${IMAGE_BASE} git --version

after_success:
  - echo "${IMAGE_BASE}"
  - echo "${IMAGE_EXT}"

after_failure: skip

before_deploy: skip

deploy:
  provider: script
  script: docker push "${IMAGE_BASE}" && docker push "${IMAGE_EXT}"
  on:
    all_branches: true

after_deploy: skip

after_script: skip
